// Code generated by options-gen v0.55.3. DO NOT EDIT.

package listenresizefile

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	eventstream "github.com/assurrussa/gowebsocket/eventstream"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	fileRepository fileRepository,
	outboxPutter outboxPutter,
	eventStream eventstream.EventStream,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.fileRepository = fileRepository
	o.outboxPutter = outboxPutter
	o.eventStream = eventStream
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("fileRepository", _validate_Options_fileRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outboxPutter", _validate_Options_outboxPutter(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_fileRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.fileRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `fileRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outboxPutter(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outboxPutter, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outboxPutter` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
