// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/service/uploadservice (interfaces: transactor,outboxPutter,fileRepository,fileStorage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/contract_mock.gen.go -package=uploadservicemocks . transactor,outboxPutter,fileRepository,fileStorage
//

// Package uploadservicemocks is a generated GoMock package.
package uploadservicemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/assurrussa/outbox/shared/types"
	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	filestorage "github.com/assurrussa/gouploads/infrastructure/storage/files"
)

// Mocktransactor is a mock of transactor interface.
type Mocktransactor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactorMockRecorder
	isgomock struct{}
}

// MocktransactorMockRecorder is the mock recorder for Mocktransactor.
type MocktransactorMockRecorder struct {
	mock *Mocktransactor
}

// NewMocktransactor creates a new mock instance.
func NewMocktransactor(ctrl *gomock.Controller) *Mocktransactor {
	mock := &Mocktransactor{ctrl: ctrl}
	mock.recorder = &MocktransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactor) EXPECT() *MocktransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *Mocktransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MocktransactorMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*Mocktransactor)(nil).RunInTx), ctx, f)
}

// MockoutboxPutter is a mock of outboxPutter interface.
type MockoutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxPutterMockRecorder
	isgomock struct{}
}

// MockoutboxPutterMockRecorder is the mock recorder for MockoutboxPutter.
type MockoutboxPutterMockRecorder struct {
	mock *MockoutboxPutter
}

// NewMockoutboxPutter creates a new mock instance.
func NewMockoutboxPutter(ctrl *gomock.Controller) *MockoutboxPutter {
	mock := &MockoutboxPutter{ctrl: ctrl}
	mock.recorder = &MockoutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxPutter) EXPECT() *MockoutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// ClearPrimary mocks base method.
func (m *MockfileRepository) ClearPrimary(ctx context.Context, objectType string, objectID, excludeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPrimary", ctx, objectType, objectID, excludeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPrimary indicates an expected call of ClearPrimary.
func (mr *MockfileRepositoryMockRecorder) ClearPrimary(ctx, objectType, objectID, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPrimary", reflect.TypeOf((*MockfileRepository)(nil).ClearPrimary), ctx, objectType, objectID, excludeID)
}

// Create mocks base method.
func (m *MockfileRepository) Create(ctx context.Context, file model.File) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, file)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockfileRepositoryMockRecorder) Create(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfileRepository)(nil).Create), ctx, file)
}

// DeleteByID mocks base method.
func (m *MockfileRepository) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockfileRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockfileRepository)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, id int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, id)
}

// SetPrimary mocks base method.
func (m *MockfileRepository) SetPrimary(ctx context.Context, id int64, objectType string, objectID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimary", ctx, id, objectType, objectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPrimary indicates an expected call of SetPrimary.
func (mr *MockfileRepositoryMockRecorder) SetPrimary(ctx, id, objectType, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimary", reflect.TypeOf((*MockfileRepository)(nil).SetPrimary), ctx, id, objectType, objectID)
}

// Update mocks base method.
func (m *MockfileRepository) Update(ctx context.Context, id int64, file model.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockfileRepositoryMockRecorder) Update(ctx, id, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockfileRepository)(nil).Update), ctx, id, file)
}

// MockfileStorage is a mock of fileStorage interface.
type MockfileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockfileStorageMockRecorder
	isgomock struct{}
}

// MockfileStorageMockRecorder is the mock recorder for MockfileStorage.
type MockfileStorageMockRecorder struct {
	mock *MockfileStorage
}

// NewMockfileStorage creates a new mock instance.
func NewMockfileStorage(ctrl *gomock.Controller) *MockfileStorage {
	mock := &MockfileStorage{ctrl: ctrl}
	mock.recorder = &MockfileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileStorage) EXPECT() *MockfileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockfileStorage) Delete(ctx context.Context, relativePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, relativePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfileStorageMockRecorder) Delete(ctx, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfileStorage)(nil).Delete), ctx, relativePath)
}

// SaveTemp mocks base method.
func (m *MockfileStorage) SaveTemp(ctx context.Context, input filestorage.SaveFileInput) (filestorage.StoredFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTemp", ctx, input)
	ret0, _ := ret[0].(filestorage.StoredFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTemp indicates an expected call of SaveTemp.
func (mr *MockfileStorageMockRecorder) SaveTemp(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTemp", reflect.TypeOf((*MockfileStorage)(nil).SaveTemp), ctx, input)
}
