// Code generated by options-gen v0.55.3. DO NOT EDIT.

package clientresizer

import (
	"context"
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	client httpClient,
	mediaImageResizerURL string,
	mediaVideoResizerURL string,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.client = client
	o.mediaImageResizerURL = mediaImageResizerURL
	o.mediaVideoResizerURL = mediaVideoResizerURL
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithImageResizerToken(opt string) OptOptionsSetter {
	return func(o *Options) { o.imageResizerToken = opt }
}

func WithVideoResizerToken(opt string) OptOptionsSetter {
	return func(o *Options) { o.videoResizerToken = opt }
}

func WithTokenProvider(opt func(context.Context) (imageToken string, videoToken string)) OptOptionsSetter {
	return func(o *Options) { o.tokenProvider = opt }
}

func WithArtifactClient(opt artifactHTTPClient) OptOptionsSetter {
	return func(o *Options) { o.artifactClient = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("client", _validate_Options_client(o)))
	errs.Add(errors461e464ebed9.NewValidationError("mediaImageResizerURL", _validate_Options_mediaImageResizerURL(o)))
	errs.Add(errors461e464ebed9.NewValidationError("mediaVideoResizerURL", _validate_Options_mediaVideoResizerURL(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_client(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.client, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `client` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_mediaImageResizerURL(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mediaImageResizerURL, "required,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `mediaImageResizerURL` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_mediaVideoResizerURL(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mediaVideoResizerURL, "required,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `mediaVideoResizerURL` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
