// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/transport/http (interfaces: TaskUploader,FileRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.gen.go -package=httpmocks . TaskUploader,FileRepository
//

// Package httpmocks is a generated GoMock package.
package httpmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	filerepo "github.com/assurrussa/gouploads/domain/files/repositories/filerepo"
	uploadservice "github.com/assurrussa/gouploads/domain/files/service/uploadservice"
)

// MockTaskUploader is a mock of TaskUploader interface.
type MockTaskUploader struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUploaderMockRecorder
	isgomock struct{}
}

// MockTaskUploaderMockRecorder is the mock recorder for MockTaskUploader.
type MockTaskUploaderMockRecorder struct {
	mock *MockTaskUploader
}

// NewMockTaskUploader creates a new mock instance.
func NewMockTaskUploader(ctrl *gomock.Controller) *MockTaskUploader {
	mock := &MockTaskUploader{ctrl: ctrl}
	mock.recorder = &MockTaskUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUploader) EXPECT() *MockTaskUploaderMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockTaskUploader) DeleteFile(ctx context.Context, req uploadservice.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockTaskUploaderMockRecorder) DeleteFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockTaskUploader)(nil).DeleteFile), ctx, req)
}

// GetFile mocks base method.
func (m *MockTaskUploader) GetFile(ctx context.Context, fileID int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, fileID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockTaskUploaderMockRecorder) GetFile(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockTaskUploader)(nil).GetFile), ctx, fileID)
}

// UploadBatch mocks base method.
func (m *MockTaskUploader) UploadBatch(ctx context.Context, req uploadservice.BatchRequest) ([]model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadBatch", ctx, req)
	ret0, _ := ret[0].([]model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadBatch indicates an expected call of UploadBatch.
func (mr *MockTaskUploaderMockRecorder) UploadBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBatch", reflect.TypeOf((*MockTaskUploader)(nil).UploadBatch), ctx, req)
}

// UploadReader mocks base method.
func (m *MockTaskUploader) UploadReader(ctx context.Context, req uploadservice.ReaderRequest, input uploadservice.ReaderUploadInput) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadReader", ctx, req, input)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadReader indicates an expected call of UploadReader.
func (mr *MockTaskUploaderMockRecorder) UploadReader(ctx, req, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadReader", reflect.TypeOf((*MockTaskUploader)(nil).UploadReader), ctx, req, input)
}

// UploadSingle mocks base method.
func (m *MockTaskUploader) UploadSingle(ctx context.Context, req uploadservice.SingleRequest) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSingle", ctx, req)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSingle indicates an expected call of UploadSingle.
func (mr *MockTaskUploaderMockRecorder) UploadSingle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSingle", reflect.TypeOf((*MockTaskUploader)(nil).UploadSingle), ctx, req)
}

// UploadStored mocks base method.
func (m *MockTaskUploader) UploadStored(ctx context.Context, req uploadservice.ReaderRequest, uploaded uploadservice.UploadedFile) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadStored", ctx, req, uploaded)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadStored indicates an expected call of UploadStored.
func (mr *MockTaskUploaderMockRecorder) UploadStored(ctx, req, uploaded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadStored", reflect.TypeOf((*MockTaskUploader)(nil).UploadStored), ctx, req, uploaded)
}

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
	isgomock struct{}
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockFileRepository) GetByID(ctx context.Context, id int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFileRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockFileRepository) List(ctx context.Context, filters filerepo.ListFilters) ([]model.File, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]model.File)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFileRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFileRepository)(nil).List), ctx, filters)
}
