// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/usecases/command/upload_file (interfaces: fileRepository,outboxPutter,fileStorage,resizeClient,transactor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=uploadfilemocks . fileRepository,outboxPutter,fileStorage,resizeClient,transactor
//

// Package uploadfilemocks is a generated GoMock package.
package uploadfilemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/assurrussa/outbox/shared/types"
	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	clientresizer "github.com/assurrussa/gouploads/domain/files/service/client_resizer"
	filestorage "github.com/assurrussa/gouploads/infrastructure/storage/files"
)

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, fileID int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, fileID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, fileID)
}

// Update mocks base method.
func (m *MockfileRepository) Update(ctx context.Context, fileID int64, file model.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, fileID, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockfileRepositoryMockRecorder) Update(ctx, fileID, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockfileRepository)(nil).Update), ctx, fileID, file)
}

// MockoutboxPutter is a mock of outboxPutter interface.
type MockoutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxPutterMockRecorder
	isgomock struct{}
}

// MockoutboxPutterMockRecorder is the mock recorder for MockoutboxPutter.
type MockoutboxPutterMockRecorder struct {
	mock *MockoutboxPutter
}

// NewMockoutboxPutter creates a new mock instance.
func NewMockoutboxPutter(ctrl *gomock.Controller) *MockoutboxPutter {
	mock := &MockoutboxPutter{ctrl: ctrl}
	mock.recorder = &MockoutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxPutter) EXPECT() *MockoutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockfileStorage is a mock of fileStorage interface.
type MockfileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockfileStorageMockRecorder
	isgomock struct{}
}

// MockfileStorageMockRecorder is the mock recorder for MockfileStorage.
type MockfileStorageMockRecorder struct {
	mock *MockfileStorage
}

// NewMockfileStorage creates a new mock instance.
func NewMockfileStorage(ctrl *gomock.Controller) *MockfileStorage {
	mock := &MockfileStorage{ctrl: ctrl}
	mock.recorder = &MockfileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileStorage) EXPECT() *MockfileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockfileStorage) Delete(ctx context.Context, relativePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, relativePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfileStorageMockRecorder) Delete(ctx, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfileStorage)(nil).Delete), ctx, relativePath)
}

// SavePersist mocks base method.
func (m *MockfileStorage) SavePersist(ctx context.Context, input filestorage.SaveFileInput) (filestorage.StoredFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePersist", ctx, input)
	ret0, _ := ret[0].(filestorage.StoredFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePersist indicates an expected call of SavePersist.
func (mr *MockfileStorageMockRecorder) SavePersist(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePersist", reflect.TypeOf((*MockfileStorage)(nil).SavePersist), ctx, input)
}

// MockresizeClient is a mock of resizeClient interface.
type MockresizeClient struct {
	ctrl     *gomock.Controller
	recorder *MockresizeClientMockRecorder
	isgomock struct{}
}

// MockresizeClientMockRecorder is the mock recorder for MockresizeClient.
type MockresizeClientMockRecorder struct {
	mock *MockresizeClient
}

// NewMockresizeClient creates a new mock instance.
func NewMockresizeClient(ctrl *gomock.Controller) *MockresizeClient {
	mock := &MockresizeClient{ctrl: ctrl}
	mock.recorder = &MockresizeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresizeClient) EXPECT() *MockresizeClientMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockresizeClient) DownloadFile(ctx context.Context, req clientresizer.RequestDownload) (clientresizer.ResponseDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, req)
	ret0, _ := ret[0].(clientresizer.ResponseDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockresizeClientMockRecorder) DownloadFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockresizeClient)(nil).DownloadFile), ctx, req)
}

// Mocktransactor is a mock of transactor interface.
type Mocktransactor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactorMockRecorder
	isgomock struct{}
}

// MocktransactorMockRecorder is the mock recorder for Mocktransactor.
type MocktransactorMockRecorder struct {
	mock *Mocktransactor
}

// NewMocktransactor creates a new mock instance.
func NewMocktransactor(ctrl *gomock.Controller) *Mocktransactor {
	mock := &Mocktransactor{ctrl: ctrl}
	mock.recorder = &MocktransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactor) EXPECT() *MocktransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *Mocktransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MocktransactorMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*Mocktransactor)(nil).RunInTx), ctx, f)
}
