// Code generated by options-gen v0.55.3. DO NOT EDIT.

package sendresizefile

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/goshared/pkg/logger"
	eventstream "github.com/assurrussa/goshared/services/event-stream"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	"github.com/assurrussa/gouploads/config"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	fileRepository fileRepository,
	remoteClient resizeClient,
	eventStream eventstream.EventStream,
	imagePipeline config.ImagePipelineConfig,
	videoPipeline config.VideoPipelineConfig,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.fileRepository = fileRepository
	o.remoteClient = remoteClient
	o.eventStream = eventStream
	o.imagePipeline = imagePipeline
	o.videoPipeline = videoPipeline
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("fileRepository", _validate_Options_fileRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("remoteClient", _validate_Options_remoteClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("imagePipeline", _validate_Options_imagePipeline(o)))
	errs.Add(errors461e464ebed9.NewValidationError("videoPipeline", _validate_Options_videoPipeline(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_fileRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.fileRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `fileRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_remoteClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.remoteClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `remoteClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_imagePipeline(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.imagePipeline, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `imagePipeline` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_videoPipeline(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.videoPipeline, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `videoPipeline` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
