// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/outbox/deleted_file (interfaces: deleteFileUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/job_mock.gen.go -package=deletedfilejobmocks . deleteFileUseCase
//

// Package deletedfilejobmocks is a generated GoMock package.
package deletedfilejobmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	deletefile "github.com/assurrussa/gouploads/domain/files/usecases/command/delete_file"
)

// MockdeleteFileUseCase is a mock of deleteFileUseCase interface.
type MockdeleteFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockdeleteFileUseCaseMockRecorder
	isgomock struct{}
}

// MockdeleteFileUseCaseMockRecorder is the mock recorder for MockdeleteFileUseCase.
type MockdeleteFileUseCaseMockRecorder struct {
	mock *MockdeleteFileUseCase
}

// NewMockdeleteFileUseCase creates a new mock instance.
func NewMockdeleteFileUseCase(ctrl *gomock.Controller) *MockdeleteFileUseCase {
	mock := &MockdeleteFileUseCase{ctrl: ctrl}
	mock.recorder = &MockdeleteFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeleteFileUseCase) EXPECT() *MockdeleteFileUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockdeleteFileUseCase) Handle(ctx context.Context, req deletefile.Request) (deletefile.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(deletefile.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockdeleteFileUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockdeleteFileUseCase)(nil).Handle), ctx, req)
}
