// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/usecases/command/upload_raw_file (interfaces: uploadService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=uploadrawfilemocks . uploadService
//

// Package uploadrawfilemocks is a generated GoMock package.
package uploadrawfilemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	uploadservice "github.com/assurrussa/gouploads/domain/files/service/uploadservice"
)

// MockuploadService is a mock of uploadService interface.
type MockuploadService struct {
	ctrl     *gomock.Controller
	recorder *MockuploadServiceMockRecorder
	isgomock struct{}
}

// MockuploadServiceMockRecorder is the mock recorder for MockuploadService.
type MockuploadServiceMockRecorder struct {
	mock *MockuploadService
}

// NewMockuploadService creates a new mock instance.
func NewMockuploadService(ctrl *gomock.Controller) *MockuploadService {
	mock := &MockuploadService{ctrl: ctrl}
	mock.recorder = &MockuploadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuploadService) EXPECT() *MockuploadServiceMockRecorder {
	return m.recorder
}

// UploadSingle mocks base method.
func (m *MockuploadService) UploadSingle(ctx context.Context, req uploadservice.SingleRequest) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSingle", ctx, req)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSingle indicates an expected call of UploadSingle.
func (mr *MockuploadServiceMockRecorder) UploadSingle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSingle", reflect.TypeOf((*MockuploadService)(nil).UploadSingle), ctx, req)
}
