// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=mocks/job_mock.gen.go -package=sendresizefilejobmocks
//

// Package sendresizefilejobmocks is a generated GoMock package.
package sendresizefilejobmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	sendresizefile "github.com/assurrussa/gouploads/domain/files/usecases/command/send_resize_file"
)

// MocksendResizeFileUseCase is a mock of sendResizeFileUseCase interface.
type MocksendResizeFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocksendResizeFileUseCaseMockRecorder
	isgomock struct{}
}

// MocksendResizeFileUseCaseMockRecorder is the mock recorder for MocksendResizeFileUseCase.
type MocksendResizeFileUseCaseMockRecorder struct {
	mock *MocksendResizeFileUseCase
}

// NewMocksendResizeFileUseCase creates a new mock instance.
func NewMocksendResizeFileUseCase(ctrl *gomock.Controller) *MocksendResizeFileUseCase {
	mock := &MocksendResizeFileUseCase{ctrl: ctrl}
	mock.recorder = &MocksendResizeFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksendResizeFileUseCase) EXPECT() *MocksendResizeFileUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocksendResizeFileUseCase) Handle(ctx context.Context, req sendresizefile.Request) (sendresizefile.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(sendresizefile.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocksendResizeFileUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocksendResizeFileUseCase)(nil).Handle), ctx, req)
}
