// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=mocks/job_mock.gen.go -package=uploadfilejobmocks
//

// Package uploadfilejobmocks is a generated GoMock package.
package uploadfilejobmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	uploadfile "github.com/assurrussa/gouploads/domain/files/usecases/command/upload_file"
)

// MockuploadFileUseCase is a mock of uploadFileUseCase interface.
type MockuploadFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuploadFileUseCaseMockRecorder
	isgomock struct{}
}

// MockuploadFileUseCaseMockRecorder is the mock recorder for MockuploadFileUseCase.
type MockuploadFileUseCaseMockRecorder struct {
	mock *MockuploadFileUseCase
}

// NewMockuploadFileUseCase creates a new mock instance.
func NewMockuploadFileUseCase(ctrl *gomock.Controller) *MockuploadFileUseCase {
	mock := &MockuploadFileUseCase{ctrl: ctrl}
	mock.recorder = &MockuploadFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuploadFileUseCase) EXPECT() *MockuploadFileUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockuploadFileUseCase) Handle(ctx context.Context, req uploadfile.Request) (uploadfile.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(uploadfile.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockuploadFileUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockuploadFileUseCase)(nil).Handle), ctx, req)
}
