// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/usecases/command/delete_file (interfaces: fileRepository,fileStorage,transactor,outboxPutter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=deletefilemocks . fileRepository,fileStorage,transactor,outboxPutter
//

// Package deletefilemocks is a generated GoMock package.
package deletefilemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/assurrussa/outbox/shared/types"
	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
)

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockfileRepository) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockfileRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockfileRepository)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, id int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, id)
}

// MockfileStorage is a mock of fileStorage interface.
type MockfileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockfileStorageMockRecorder
	isgomock struct{}
}

// MockfileStorageMockRecorder is the mock recorder for MockfileStorage.
type MockfileStorageMockRecorder struct {
	mock *MockfileStorage
}

// NewMockfileStorage creates a new mock instance.
func NewMockfileStorage(ctrl *gomock.Controller) *MockfileStorage {
	mock := &MockfileStorage{ctrl: ctrl}
	mock.recorder = &MockfileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileStorage) EXPECT() *MockfileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockfileStorage) Delete(ctx context.Context, relativePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, relativePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfileStorageMockRecorder) Delete(ctx, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfileStorage)(nil).Delete), ctx, relativePath)
}

// DeleteBatch mocks base method.
func (m *MockfileStorage) DeleteBatch(ctx context.Context, relativePaths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, relativePaths)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockfileStorageMockRecorder) DeleteBatch(ctx, relativePaths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockfileStorage)(nil).DeleteBatch), ctx, relativePaths)
}

// Mocktransactor is a mock of transactor interface.
type Mocktransactor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactorMockRecorder
	isgomock struct{}
}

// MocktransactorMockRecorder is the mock recorder for Mocktransactor.
type MocktransactorMockRecorder struct {
	mock *Mocktransactor
}

// NewMocktransactor creates a new mock instance.
func NewMocktransactor(ctrl *gomock.Controller) *Mocktransactor {
	mock := &Mocktransactor{ctrl: ctrl}
	mock.recorder = &MocktransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactor) EXPECT() *MocktransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *Mocktransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MocktransactorMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*Mocktransactor)(nil).RunInTx), ctx, f)
}

// MockoutboxPutter is a mock of outboxPutter interface.
type MockoutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxPutterMockRecorder
	isgomock struct{}
}

// MockoutboxPutterMockRecorder is the mock recorder for MockoutboxPutter.
type MockoutboxPutterMockRecorder struct {
	mock *MockoutboxPutter
}

// NewMockoutboxPutter creates a new mock instance.
func NewMockoutboxPutter(ctrl *gomock.Controller) *MockoutboxPutter {
	mock := &MockoutboxPutter{ctrl: ctrl}
	mock.recorder = &MockoutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxPutter) EXPECT() *MockoutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}
