// Code generated by options-gen v0.58.0. DO NOT EDIT.

package filerepo

import (
	fmt461e464ebed9 "fmt"

	pgsql "github.com/assurrussa/outbox/backends/pgsql/storage"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	pgsql pgsql.Client,
	trxManager pgsql.TxManager,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.pgsql = pgsql
	o.trxManager = trxManager

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("pgsql", _validate_Options_pgsql(o)))
	errs.Add(errors461e464ebed9.NewValidationError("trxManager", _validate_Options_trxManager(o)))
	return errs.AsError()
}

func _validate_Options_pgsql(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.pgsql, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `pgsql` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_trxManager(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.trxManager, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `trxManager` did not pass the test: %w", err)
	}
	return nil
}
