// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/service/client_resizer (interfaces: httpClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.gen.go -package=clientresizermocks . httpClient
//

// Package clientresizermocks is a generated GoMock package.
package clientresizermocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	transporthttp "github.com/assurrussa/goshared/pkg/transport/http"
	gomock "go.uber.org/mock/gomock"
)

// MockhttpClient is a mock of httpClient interface.
type MockhttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockhttpClientMockRecorder
	isgomock struct{}
}

// MockhttpClientMockRecorder is the mock recorder for MockhttpClient.
type MockhttpClientMockRecorder struct {
	mock *MockhttpClient
}

// NewMockhttpClient creates a new mock instance.
func NewMockhttpClient(ctrl *gomock.Controller) *MockhttpClient {
	mock := &MockhttpClient{ctrl: ctrl}
	mock.recorder = &MockhttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpClient) EXPECT() *MockhttpClientMockRecorder {
	return m.recorder
}

// DoWithRequest mocks base method.
func (m *MockhttpClient) DoWithRequest(ctx context.Context, request transporthttp.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithRequest", ctx, request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoWithRequest indicates an expected call of DoWithRequest.
func (mr *MockhttpClientMockRecorder) DoWithRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithRequest", reflect.TypeOf((*MockhttpClient)(nil).DoWithRequest), ctx, request)
}

// DoWithRequestAndParse mocks base method.
func (m *MockhttpClient) DoWithRequestAndParse(ctx context.Context, request transporthttp.Request, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithRequestAndParse", ctx, request, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoWithRequestAndParse indicates an expected call of DoWithRequestAndParse.
func (mr *MockhttpClientMockRecorder) DoWithRequestAndParse(ctx, request, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithRequestAndParse", reflect.TypeOf((*MockhttpClient)(nil).DoWithRequestAndParse), ctx, request, data)
}
