// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.gen.go -package=clientresizermocks
//

// Package clientresizermocks is a generated GoMock package.
package clientresizermocks

import (
	context "context"
	http0 "net/http"
	reflect "reflect"

	http "github.com/assurrussa/goshared/pkg/transport/http"
	gomock "go.uber.org/mock/gomock"
)

// MockhttpClient is a mock of httpClient interface.
type MockhttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockhttpClientMockRecorder
	isgomock struct{}
}

// MockhttpClientMockRecorder is the mock recorder for MockhttpClient.
type MockhttpClientMockRecorder struct {
	mock *MockhttpClient
}

// NewMockhttpClient creates a new mock instance.
func NewMockhttpClient(ctrl *gomock.Controller) *MockhttpClient {
	mock := &MockhttpClient{ctrl: ctrl}
	mock.recorder = &MockhttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpClient) EXPECT() *MockhttpClientMockRecorder {
	return m.recorder
}

// DoWithRequestAndParse mocks base method.
func (m *MockhttpClient) DoWithRequestAndParse(ctx context.Context, request http.Request, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithRequestAndParse", ctx, request, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoWithRequestAndParse indicates an expected call of DoWithRequestAndParse.
func (mr *MockhttpClientMockRecorder) DoWithRequestAndParse(ctx, request, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithRequestAndParse", reflect.TypeOf((*MockhttpClient)(nil).DoWithRequestAndParse), ctx, request, data)
}

// MockartifactHTTPClient is a mock of artifactHTTPClient interface.
type MockartifactHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockartifactHTTPClientMockRecorder
	isgomock struct{}
}

// MockartifactHTTPClientMockRecorder is the mock recorder for MockartifactHTTPClient.
type MockartifactHTTPClientMockRecorder struct {
	mock *MockartifactHTTPClient
}

// NewMockartifactHTTPClient creates a new mock instance.
func NewMockartifactHTTPClient(ctrl *gomock.Controller) *MockartifactHTTPClient {
	mock := &MockartifactHTTPClient{ctrl: ctrl}
	mock.recorder = &MockartifactHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockartifactHTTPClient) EXPECT() *MockartifactHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockartifactHTTPClient) Do(request *http0.Request) (*http0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", request)
	ret0, _ := ret[0].(*http0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockartifactHTTPClientMockRecorder) Do(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockartifactHTTPClient)(nil).Do), request)
}
