// Code generated by options-gen v0.55.3. DO NOT EDIT.

package cleanertusuploads

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	cleaner cleaner,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.cleaner = cleaner

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("cleaner", _validate_Options_cleaner(o)))
	return errs.AsError()
}

func _validate_Options_cleaner(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.cleaner, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `cleaner` did not pass the test: %w", err)
	}
	return nil
}
