// Code generated by options-gen v0.55.3. DO NOT EDIT.

package uploadfile

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/goshared/pkg/logger"
	eventstream "github.com/assurrussa/goshared/services/event-stream"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	transactor transactor,
	fileRepository fileRepository,
	resizeClient resizeClient,
	eventStream eventstream.EventStream,
	logger logger.Logger,
	storage fileStorage,
	outbox outboxPutter,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.baseFolder = "media/v1"

	o.transactor = transactor
	o.fileRepository = fileRepository
	o.resizeClient = resizeClient
	o.eventStream = eventStream
	o.logger = logger
	o.storage = storage
	o.outbox = outbox

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithBaseFolder(opt string) OptOptionsSetter {
	return func(o *Options) { o.baseFolder = opt }
}

func WithDeliveryBaseURL(opt string) OptOptionsSetter {
	return func(o *Options) { o.deliveryBaseURL = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("transactor", _validate_Options_transactor(o)))
	errs.Add(errors461e464ebed9.NewValidationError("fileRepository", _validate_Options_fileRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("resizeClient", _validate_Options_resizeClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("storage", _validate_Options_storage(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outbox", _validate_Options_outbox(o)))
	errs.Add(errors461e464ebed9.NewValidationError("deliveryBaseURL", _validate_Options_deliveryBaseURL(o)))
	return errs.AsError()
}

func _validate_Options_transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `transactor` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_fileRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.fileRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `fileRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_resizeClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.resizeClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `resizeClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_storage(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.storage, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `storage` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outbox(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outbox, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outbox` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_deliveryBaseURL(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.deliveryBaseURL, "omitempty,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `deliveryBaseURL` did not pass the test: %w", err)
	}
	return nil
}
