// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=sendresizefilemocks
//

// Package sendresizefilemocks is a generated GoMock package.
package sendresizefilemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	clientresizer "github.com/assurrussa/gouploads/domain/files/service/client_resizer"
)

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, taskID int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, taskID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, taskID)
}

// MockresizeClient is a mock of resizeClient interface.
type MockresizeClient struct {
	ctrl     *gomock.Controller
	recorder *MockresizeClientMockRecorder
	isgomock struct{}
}

// MockresizeClientMockRecorder is the mock recorder for MockresizeClient.
type MockresizeClientMockRecorder struct {
	mock *MockresizeClient
}

// NewMockresizeClient creates a new mock instance.
func NewMockresizeClient(ctrl *gomock.Controller) *MockresizeClient {
	mock := &MockresizeClient{ctrl: ctrl}
	mock.recorder = &MockresizeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresizeClient) EXPECT() *MockresizeClientMockRecorder {
	return m.recorder
}

// SendResize mocks base method.
func (m *MockresizeClient) SendResize(ctx context.Context, req clientresizer.Request) (clientresizer.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResize", ctx, req)
	ret0, _ := ret[0].(clientresizer.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendResize indicates an expected call of SendResize.
func (mr *MockresizeClientMockRecorder) SendResize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResize", reflect.TypeOf((*MockresizeClient)(nil).SendResize), ctx, req)
}
