// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/usecases/command/send_resize_file (interfaces: fileRepository,resizeClient,outboxPutter,resultHandler,sourceURLResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=sendresizefilemocks . fileRepository,resizeClient,outboxPutter,resultHandler,sourceURLResolver
//

// Package sendresizefilemocks is a generated GoMock package.
package sendresizefilemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/assurrussa/outbox/shared/types"
	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
	clientresizer "github.com/assurrussa/gouploads/domain/files/service/client_resizer"
	listenresizefile "github.com/assurrussa/gouploads/domain/files/usecases/command/listen_resize_file"
)

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, taskID int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, taskID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, taskID)
}

// MockresizeClient is a mock of resizeClient interface.
type MockresizeClient struct {
	ctrl     *gomock.Controller
	recorder *MockresizeClientMockRecorder
	isgomock struct{}
}

// MockresizeClientMockRecorder is the mock recorder for MockresizeClient.
type MockresizeClientMockRecorder struct {
	mock *MockresizeClient
}

// NewMockresizeClient creates a new mock instance.
func NewMockresizeClient(ctrl *gomock.Controller) *MockresizeClient {
	mock := &MockresizeClient{ctrl: ctrl}
	mock.recorder = &MockresizeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresizeClient) EXPECT() *MockresizeClientMockRecorder {
	return m.recorder
}

// GetJob mocks base method.
func (m *MockresizeClient) GetJob(ctx context.Context, req clientresizer.JobRequest) (clientresizer.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, req)
	ret0, _ := ret[0].(clientresizer.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockresizeClientMockRecorder) GetJob(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockresizeClient)(nil).GetJob), ctx, req)
}

// SendResize mocks base method.
func (m *MockresizeClient) SendResize(ctx context.Context, req clientresizer.Request) (clientresizer.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResize", ctx, req)
	ret0, _ := ret[0].(clientresizer.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendResize indicates an expected call of SendResize.
func (mr *MockresizeClientMockRecorder) SendResize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResize", reflect.TypeOf((*MockresizeClient)(nil).SendResize), ctx, req)
}

// MockoutboxPutter is a mock of outboxPutter interface.
type MockoutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxPutterMockRecorder
	isgomock struct{}
}

// MockoutboxPutterMockRecorder is the mock recorder for MockoutboxPutter.
type MockoutboxPutterMockRecorder struct {
	mock *MockoutboxPutter
}

// NewMockoutboxPutter creates a new mock instance.
func NewMockoutboxPutter(ctrl *gomock.Controller) *MockoutboxPutter {
	mock := &MockoutboxPutter{ctrl: ctrl}
	mock.recorder = &MockoutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxPutter) EXPECT() *MockoutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockresultHandler is a mock of resultHandler interface.
type MockresultHandler struct {
	ctrl     *gomock.Controller
	recorder *MockresultHandlerMockRecorder
	isgomock struct{}
}

// MockresultHandlerMockRecorder is the mock recorder for MockresultHandler.
type MockresultHandlerMockRecorder struct {
	mock *MockresultHandler
}

// NewMockresultHandler creates a new mock instance.
func NewMockresultHandler(ctrl *gomock.Controller) *MockresultHandler {
	mock := &MockresultHandler{ctrl: ctrl}
	mock.recorder = &MockresultHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresultHandler) EXPECT() *MockresultHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockresultHandler) Handle(ctx context.Context, req listenresizefile.Request) (listenresizefile.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(listenresizefile.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockresultHandlerMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockresultHandler)(nil).Handle), ctx, req)
}

// MocksourceURLResolver is a mock of sourceURLResolver interface.
type MocksourceURLResolver struct {
	ctrl     *gomock.Controller
	recorder *MocksourceURLResolverMockRecorder
	isgomock struct{}
}

// MocksourceURLResolverMockRecorder is the mock recorder for MocksourceURLResolver.
type MocksourceURLResolverMockRecorder struct {
	mock *MocksourceURLResolver
}

// NewMocksourceURLResolver creates a new mock instance.
func NewMocksourceURLResolver(ctrl *gomock.Controller) *MocksourceURLResolver {
	mock := &MocksourceURLResolver{ctrl: ctrl}
	mock.recorder = &MocksourceURLResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceURLResolver) EXPECT() *MocksourceURLResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MocksourceURLResolver) Resolve(ctx context.Context, source string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, source)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MocksourceURLResolverMockRecorder) Resolve(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MocksourceURLResolver)(nil).Resolve), ctx, source)
}
