// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=cleanertusuploadsmocks
//

// Package cleanertusuploadsmocks is a generated GoMock package.
package cleanertusuploadsmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// Mockcleaner is a mock of cleaner interface.
type Mockcleaner struct {
	ctrl     *gomock.Controller
	recorder *MockcleanerMockRecorder
	isgomock struct{}
}

// MockcleanerMockRecorder is the mock recorder for Mockcleaner.
type MockcleanerMockRecorder struct {
	mock *Mockcleaner
}

// NewMockcleaner creates a new mock instance.
func NewMockcleaner(ctrl *gomock.Controller) *Mockcleaner {
	mock := &Mockcleaner{ctrl: ctrl}
	mock.recorder = &MockcleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcleaner) EXPECT() *MockcleanerMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *Mockcleaner) Cleanup(ctx context.Context, before time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, before)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockcleanerMockRecorder) Cleanup(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*Mockcleaner)(nil).Cleanup), ctx, before)
}
