// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=listenresizefilemocks
//

// Package listenresizefilemocks is a generated GoMock package.
package listenresizefilemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/assurrussa/outbox/shared/types"
	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/gouploads/domain/files/model"
)

// MockfileRepository is a mock of fileRepository interface.
type MockfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepositoryMockRecorder
	isgomock struct{}
}

// MockfileRepositoryMockRecorder is the mock recorder for MockfileRepository.
type MockfileRepositoryMockRecorder struct {
	mock *MockfileRepository
}

// NewMockfileRepository creates a new mock instance.
func NewMockfileRepository(ctrl *gomock.Controller) *MockfileRepository {
	mock := &MockfileRepository{ctrl: ctrl}
	mock.recorder = &MockfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepository) EXPECT() *MockfileRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfileRepository) GetByID(ctx context.Context, taskID int64) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, taskID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepositoryMockRecorder) GetByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepository)(nil).GetByID), ctx, taskID)
}

// MockoutboxPutter is a mock of outboxPutter interface.
type MockoutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxPutterMockRecorder
	isgomock struct{}
}

// MockoutboxPutterMockRecorder is the mock recorder for MockoutboxPutter.
type MockoutboxPutterMockRecorder struct {
	mock *MockoutboxPutter
}

// NewMockoutboxPutter creates a new mock instance.
func NewMockoutboxPutter(ctrl *gomock.Controller) *MockoutboxPutter {
	mock := &MockoutboxPutter{ctrl: ctrl}
	mock.recorder = &MockoutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxPutter) EXPECT() *MockoutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockfailureRepository is a mock of failureRepository interface.
type MockfailureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfailureRepositoryMockRecorder
	isgomock struct{}
}

// MockfailureRepositoryMockRecorder is the mock recorder for MockfailureRepository.
type MockfailureRepositoryMockRecorder struct {
	mock *MockfailureRepository
}

// NewMockfailureRepository creates a new mock instance.
func NewMockfailureRepository(ctrl *gomock.Controller) *MockfailureRepository {
	mock := &MockfailureRepository{ctrl: ctrl}
	mock.recorder = &MockfailureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfailureRepository) EXPECT() *MockfailureRepositoryMockRecorder {
	return m.recorder
}

// MarkMediaFailed mocks base method.
func (m *MockfailureRepository) MarkMediaFailed(ctx context.Context, fileID int64) (model.File, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMediaFailed", ctx, fileID)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MarkMediaFailed indicates an expected call of MarkMediaFailed.
func (mr *MockfailureRepositoryMockRecorder) MarkMediaFailed(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMediaFailed", reflect.TypeOf((*MockfailureRepository)(nil).MarkMediaFailed), ctx, fileID)
}
