// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.gen.go -package=rcusettingsmocks
//

// Package rcusettingsmocks is a generated GoMock package.
package rcusettingsmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	rcusettings "github.com/assurrussa/gouploads/domain/files/cache/rcu/settings"
)

// MocksettingsUseCase is a mock of settingsUseCase interface.
type MocksettingsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocksettingsUseCaseMockRecorder
	isgomock struct{}
}

// MocksettingsUseCaseMockRecorder is the mock recorder for MocksettingsUseCase.
type MocksettingsUseCaseMockRecorder struct {
	mock *MocksettingsUseCase
}

// NewMocksettingsUseCase creates a new mock instance.
func NewMocksettingsUseCase(ctrl *gomock.Controller) *MocksettingsUseCase {
	mock := &MocksettingsUseCase{ctrl: ctrl}
	mock.recorder = &MocksettingsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksettingsUseCase) EXPECT() *MocksettingsUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocksettingsUseCase) Handle(ctx context.Context) (rcusettings.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx)
	ret0, _ := ret[0].(rcusettings.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocksettingsUseCaseMockRecorder) Handle(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocksettingsUseCase)(nil).Handle), ctx)
}
