// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gouploads/domain/files/outbox/listen_resize_file (interfaces: listenResizeFileUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/job_mock.gen.go -package=listenresizefilejobmocks . listenResizeFileUseCase
//

// Package listenresizefilejobmocks is a generated GoMock package.
package listenresizefilejobmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	listenresizefile "github.com/assurrussa/gouploads/domain/files/usecases/command/listen_resize_file"
)

// MocklistenResizeFileUseCase is a mock of listenResizeFileUseCase interface.
type MocklistenResizeFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistenResizeFileUseCaseMockRecorder
	isgomock struct{}
}

// MocklistenResizeFileUseCaseMockRecorder is the mock recorder for MocklistenResizeFileUseCase.
type MocklistenResizeFileUseCaseMockRecorder struct {
	mock *MocklistenResizeFileUseCase
}

// NewMocklistenResizeFileUseCase creates a new mock instance.
func NewMocklistenResizeFileUseCase(ctrl *gomock.Controller) *MocklistenResizeFileUseCase {
	mock := &MocklistenResizeFileUseCase{ctrl: ctrl}
	mock.recorder = &MocklistenResizeFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistenResizeFileUseCase) EXPECT() *MocklistenResizeFileUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistenResizeFileUseCase) Handle(ctx context.Context, req listenresizefile.Request) (listenresizefile.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(listenresizefile.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistenResizeFileUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistenResizeFileUseCase)(nil).Handle), ctx, req)
}
