// Code generated by options-gen v0.55.3. DO NOT EDIT.

package uploadservice

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	"github.com/assurrussa/gouploads/domain/files/shared"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	txManager transactor,
	outbox outboxPutter,
	fileRepo fileRepository,
	logger logger.Logger,
	storage fileStorage,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from func
	defaultOpts := getDefaultOptions()
	o.txManager = defaultOpts.txManager
	o.outbox = defaultOpts.outbox
	o.fileRepo = defaultOpts.fileRepo
	o.logger = defaultOpts.logger
	o.storage = defaultOpts.storage
	o.dirPrefix = defaultOpts.dirPrefix
	o.dirTempPrefix = defaultOpts.dirTempPrefix
	o.validators = defaultOpts.validators

	o.txManager = txManager
	o.outbox = outbox
	o.fileRepo = fileRepo
	o.logger = logger
	o.storage = storage

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithDirPrefix(opt shared.FolderPrefixPath) OptOptionsSetter {
	return func(o *Options) { o.dirPrefix = opt }
}

func WithDirTempPrefix(opt shared.FolderPrefixPath) OptOptionsSetter {
	return func(o *Options) { o.dirTempPrefix = opt }
}

func WithValidators(opt []UploadValidator) OptOptionsSetter {
	return func(o *Options) { o.validators = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("txManager", _validate_Options_txManager(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outbox", _validate_Options_outbox(o)))
	errs.Add(errors461e464ebed9.NewValidationError("fileRepo", _validate_Options_fileRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("storage", _validate_Options_storage(o)))
	return errs.AsError()
}

func _validate_Options_txManager(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.txManager, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `txManager` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outbox(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outbox, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outbox` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_fileRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.fileRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `fileRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_storage(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.storage, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `storage` did not pass the test: %w", err)
	}
	return nil
}
